baseurl = "https://creio.github.io/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
rssLimit = 10
summaryLength = 25
[pagination]
  disableAliases = true
  pagerSize = 10
  path = 'page'

locale = 'ru'

## Multilingual
defaultContentLanguage = 'ru'
# defaultContentLanguageInSubdir = true
# disableDefaultLanguageRedirect = false
# disableLanguages = ['en', 'de', 'nl']
## check ./config/languages.toml

[imaging]
  anchor = "Center"
  bgColor = "#ffffff"
  compression = "lossy"
  quality = 80
  resampleFilter = "Lanczos"
  [imaging.webp]
    hint = "photo"
    method = 2
    useSharpYuv = false

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "SITEMAP"]
section = ["HTML", "RSS", "SITEMAP"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for section sitemap.xml
[outputFormats.SITEMAP]
mediaType = "application/xml"
baseName = "sitemap"
isHTML = false
isPlainText = true
noUgly = true
rel  = "sitemap"

[caches]
  [caches.modules]
    maxAge = "10s"
    dir = ":cacheDir/:project"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  contributor = "contributors"
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/posts/:slugorcontentbasename/"
# docs = "/docs/1.0/:sections[1:]/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 50
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "tags"
    weight = 100
    [[related.indices]]
    name = "categories"
    weight = 80
    [[related.indices]]
    name = "date"
    weight = 50

[module]
  [module.hugoVersion]
    extended = true
    min = "0.103.0"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "node_modules/flexsearch"
    target = "assets/js/vendor/flexsearch"
  [[module.mounts]]
    source = "node_modules/@thulite/images/layouts"
    target = "layouts"
  [[module.mounts]]
    source = "node_modules/@thulite/seo/layouts"
    target = "layouts"
