name: Notify Telegram

on:
  # discussion:
  #   types: [created, edited, answered]
  discussion_comment:
    types: [created]
  # issue_comment:
  #   types:
  #     - created
  # issues:
  #   types: [opened, reopened]
  # pull_request:
  #   types: [opened, closed, editedreopened]
  # pull_request_review_comment:
  #   types:
  #     - created
  # push:
  #   branches:
  #     - master

# Body: ${{ github.event.comment.body }}
jobs:
  tg_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: cbrgm/telegram-github-action@v1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          parse-mode: markdown
          disable-web-page-preview: true
          message: |
            🚀 New Discussion Comment!
            Title: ${{ github.event.discussion.title }}
            Author: ${{ github.event.comment.user.login }}
            Comment URL: [ссылка](${{ github.event.comment.html_url }})
            Body: ${{ github.event.comment.body }}
